FROM registry.redhat.io/ubi9/nodejs-22:latest AS web-builder

USER 0

ENV HUSKY=0
COPY web/package*.json web/
COPY Makefile Makefile
RUN make install-frontend-ci-clean

COPY web/ web/
RUN make build-frontend

FROM registry.access.redhat.com/ubi9/go-toolset:1.26 AS go-builder

WORKDIR /opt/app-root

COPY Makefile Makefile
COPY go.mod go.mod
COPY go.sum go.sum

RUN make install-backend

COPY config/ config/
COPY cmd/ cmd/
COPY pkg/ pkg/

ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1

RUN make build-backend BUILD_OPTS="-tags strictfipsruntime"

FROM registry.access.redhat.com/ubi9/ubi-minimal

USER 1001

COPY --from=web-builder /opt/app-root/src/web/dist ./web/dist
COPY --from=go-builder /opt/app-root/plugin-backend ./
COPY --from=go-builder /opt/app-root/config ./config

ENTRYPOINT ["./plugin-backend"]
