FROM cypress/included:13.6.5

USER 1001

WORKDIR /usr/src/app

ENV CYPRESS_CACHE_FOLDER=/usr/src/app/.cache

RUN mkdir -p /usr/src/app/.cache
RUN chmod 775 -R /usr/src/app/.cache

ENV HUSKY=0

COPY web/package*.json .
RUN npm ci

COPY web/ /usr/src/app/

RUN mkdir -p /.config
RUN chmod 775 -R /.config

RUN npm run build:standalone

ENTRYPOINT ["npm", "run", "test:e2e"]
