FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.24 AS web-builder

WORKDIR /opt/app-root

USER 0
RUN chgrp -R 0 /opt/app-root
RUN chmod -R g+rw /opt/app-root
RUN mkdir /.devspace
RUN chgrp -R 0 /.devspace
RUN chmod -R g+rw /.devspace

ENV HUSKY=0

COPY Makefile Makefile
COPY go.mod go.mod
COPY go.sum go.sum

RUN make install-backend

COPY config/ config/
COPY cmd/ cmd/
COPY pkg/ pkg/

RUN make build-backend

ENTRYPOINT ["make", "start-devspace-backend"]
