export enum TestIds {
  TimeRangeDropdown = 'TimeRangeDropdown',
  RefreshIntervalDropdown = 'RefreshIntervalDropdown',
  SyncButton = 'SyncButton',
  LogsHistogram = 'LogsHistogram',
  LogsTable = 'LogsTable',
  LogsMetrics = 'LogsMetrics',
  LogsQueryInput = 'LogsQueryInput',
  ExecuteQueryButton = 'ExecuteQueryButton',
  ExecuteVolumeButton = 'ExecuteVolumeButton',
  TenantToggle = 'TenantToggle',
  SeverityDropdown = 'SeverityDropdown',
  ToogleStreamingButton = 'ToogleStreamingButton',
  ShowQueryToggle = 'ShowQueryToggle',
  ShowStatsToggle = 'ShowStatsToggle',
  LogsStats = 'LogsStats',
  AttributeFilters = 'AttributeFilters',
  TimeRangeSelectModal = 'TimeRangeSelectModal',
  TimeRangeDropdownSaveButton = 'TimeRangeDropdownSaveButton',
  ToggleHistogramButton = 'ToggleHistogramButton',
  AvailableAttributes = 'AvailableAttributes',
  AttributeOptions = 'AttributeOptions',
  NamespaceDropdown = 'NamespaceDropdown',
  NamespaceToggle = 'NamespaceToggle',
  SchemaToggle = 'SchemaToggle',
}
