version: "3.9"

networks:
  inner:

services:
  loki:
    image: grafana/loki:3.1.0
    ports:
      - 3200:3100
    restart: unless-stopped
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml
      - ./docker-compose-logs:/var/log
      - ./loki/rules:/loki/rules
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - inner

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - ./docker-compose-logs:/var/log
      - ./loki/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - inner

  log-generator:
    image: mingrammer/flog:0.4.3
    restart: unless-stopped
    volumes:
      - ./docker-compose-logs:/var/log
    command:
      - --loop
      - --format=json
      - --type=log
      - --number=10
      - --delay=100ms
      - --output=/var/log/fake.log
    networks:
      - inner

  loki-proxy:
    image: nginx:alpine
    ports:
      - 3100:80
    volumes:
      - ./proxy.conf:/etc/nginx/templates/default.conf.template
    restart: unless-stopped
    networks:
      - inner
